config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    put :email, on: :member #for email action in todo_lists_controler
    resources :todo_items do
      member do 
        patch :complete
      end
    end
  end


  root 'pages#home'


end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
  						length: { minimum: 2 }


  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }


  def completed? 
  	!completed_at.blank?
  end

  def toggle_completion!
  	if completed?
  		update_attribute(:completed_at, nil)
  	else
  		update_attribute(:completed_at, Time.now)
  	end
  end
  


end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  before_action :require_user
  before_action :find_todo_list
  before_action :set_back_link, except: [:index]

  def index
    go_back_link_to todo_lists_path
  end


  def new
  	@todo_item = @todo_list.todo_items.new
  end


  def create
  	@todo_item = @todo_list.todo_items.new(todo_item_params)
  	if @todo_item.save
  		flash[:success] = "Added todo list item."
  		redirect_to todo_list_todo_items_path
  	else
  		flash[:error] = "There was a problem adding that todo list item."
  		render action: :new
  	end
  end


  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end


  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end
  

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted."
    end
    redirect_to todo_list_todo_items_path
  end


  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.toggle_completion!
    redirect_to todo_list_todo_items_path, notice: "Todo item updated."
  end


# ===========

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end



  private

  def set_back_link
      go_back_link_to todo_list_todo_items_path(@todo_list)
    end

  def find_todo_list
    @todo_list = current_user.todo_lists.find(params[:todo_list_id])
  end

  def todo_item_params
  	params[:todo_item].permit(:content)
  end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_blank_slate.html.erb
<!-- BLANK SLATE WHEN ITEMS ARE EMPTY -->
<div class="row blank-slate">
	<div class="small-12 small-centered columns">
	  <p>You don't have any todo items!</p>
	  <%= link_to "Add items", new_todo_list_todo_item_path(@todo_list), class: "button radius" %>
	</div>
</div>

app/views/todo_items/_form.html.erb
<%= form.text_field :content %>

<%= form.submit "Save" %>

app/views/todo_items/_todo_item.html.erb
<li id="<%= dom_id(todo_item) %>" class="todo-item row">
	<div class="small-2 medium-1 columns checkmark">
		<% if todo_item.completed? %>
			<%= link_to "Mark Incomplete", complete_todo_list_todo_item_path(todo_item), method: :patch, class: "icon-check checked hide-text", title: "Mark Incomplete" %>
		<% else %>
			<%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch, class: "icon-check unchecked hide-text", title: "Mark Complete" %>
		<% end %>
	</div>

	<div class="small-10 medium-11 columns truncate todo-content <%= "completed" if todo_item.completed? %>" title="Edit">
		<%= link_to todo_item.content, edit_todo_list_todo_item_path(todo_item) %>
	</div>
</li>

app/views/todo_items/edit.html.erb
<%= title "Editing #{@todo_list.title} Item" %>

<%= form_for [@todo_list, @todo_item], builder: FoundationFormBuilder do |form| %>
  <%= render partial: 'form', locals: { form: form } %> <!-- send variables to form -->
<% end %>

<div class="row">
	<div class="small-12 small-centered columns">
		<%= link_to "Delete", todo_list_todo_item_path(@todo_list, @todo_item), method: :delete, data: { confirm: "Are you sure?" }, class: "button radius expand alert" %>
	</div>
</div>

app/views/todo_items/index.html.erb
<%= content_for(:title) do %><%= @todo_list.title %> | <% end %>

<!-- TITLE AND FUNCTIONALITY BUTTONS -->

<div class="row collapse todo-list-title">
	<div class="small-11 columns">
		<h2 class="page-title truncate"><%= @todo_list.title %></h2>
	</div>
	<div class="small-1 columns">
		<span class="fa fa-caret-down">
	</div>
</div>

<!-- toggle hide class -->
<div class="row hide" id="todo-list-functions">
	<div class="small-4 columns">
		<%= link_to edit_todo_list_path(@todo_list), class: "button expand radius outline" do %>
			<span class="fa fa-edit"></span>
			Edit
		<% end %>
	</div>
	<div class="small-4 columns">
		<%= link_to edit_todo_list_path(@todo_list), class: "button expand radius outline", data: { "reveal-id" => "email-modal" } do %>
			<span class="fa fa-envelope-o"></span>
			Email
		<% end %>
	</div>
	<div class="small-4 columns">
		<%= link_to todo_list_path(@todo_list), class: "button expand radius outline alert", method: :delete, data: { confirm: "Are you sure you want to delete this list? There is no undo."} do %>
			<span class="fa fa-trash-o"></span>
			Delete
		<% end %>
	</div>
</div>


<!-- TODO ITEMS LISTING, MAIN CONTENT -->

<% if @todo_list.todo_items.size > 0 %>

	<ul class="list todo-items no-bullet">
		<%= render partial: "todo_item", collection: @todo_list.todo_items %>
	</ul>

<% else %>
	<%= render partial: 'blank_slate' %>
<% end %>


<!-- MODAL FOR EMAIL ADDRESS DESTINATION -->
<div id="email-modal" class="reveal-modal tiny" data-reveal>
	<a class="close-reveal-modal">&#215;</a>
	<%= form_tag email_todo_list_path(@todo_list), method: :put do %>
		<%= label_tag :to, "What email address would you like to send this to?" %>
		<%= text_field_tag :to %>
		<br>
		<%= submit_tag "Send List", class: "button radius medium expand submit" %>
	<% end %>
</div>

app/views/todo_items/new.html.erb
<%= title "Add Todo Item, #{@todo_list.title}" %>

<%= form_for [@todo_list, @todo_item], builder: FoundationFormBuilder do |form| %>
  <%= render partial: 'form', locals: { form: form } %> <!-- send variables to form -->
<% end %>