config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    put :email, on: :member #for email action in todo_lists_controler
    resources :todo_items do
      member do 
        patch :complete
      end
    end
  end


  root 'pages#home'


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
      if params[:remember_me]
        signed_token = Rails.application.message_verifier(:remember_me).generate(user.id)
        cookies.permanent.signed[:remember_me_token] = signed_token
      end
  		session[:user_id] = user.id
  		flash[:success] = "Thanks for logging in!" 
  		redirect_to todo_lists_path
  	else
  		flash[:error] = "There was a problem loggin in. Please check your email and password."
  		render action: 'new'
  	end
  end

  

  def destroy
    session[:user_id] = nil
    cookies.delete(:remember_me_token)
    reset_session
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<%= title "Sign In" %>

<%= form_tag user_sessions_path do %>

<div class="row">
  <div class="small-12 columns">
    <%= label_tag :email, "Email Address" %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= text_field_tag :email, params[:email] %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= label_tag :password, "Password" %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= password_field_tag :password %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= check_box_tag :remember_me %>
    <%= label_tag :remember_me, "Remember me?" %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= submit_tag "Sign In", class: "button expand radius" %>
    </div>
</div>

<div class="row">
  <%= link_to "Forgot Password?", new_password_reset_path, class: "small-6 columns text-left" %>
  <%= link_to "Sign Up", new_user_path, class: "small-6 columns text-right" %>



<% end %>